title: "Werner Robitza"
subtitle: a.k.a. slhck
email: werner.robitza@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://slhck.info" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: slhck
github_username:  slhck

# Build settings
markdown: kramdown
# theme: minima  # Theme vendored into project
gems:
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
